import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { getThemeCookies } from "@/helpers/theme";
import ThemeButton from "@/components/ThemeButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await getThemeCookies();
  return (
    <html lang="en" className={theme}>
      <body className={`${inter.className} bg-white dark:bg-black`}>
        <header className="flex items-center gap-[30px]">
          <Image
            src="/Greenfair.jpg"
            alt="A kind of tree that has some leaves"
            width={100}
            height={80}
            className=""
          />
          <ul className="flex gap-[30px] text-black dark:text-white">
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="/service">Services {``}</a>
            </li>
            <li>
              <a href="/about">About us</a>
            </li>
            <li>
              <a href="/teams">Teams</a>
            </li>
            <li>
              <ThemeButton />
            </li>
          </ul>
        </header>
        {children}
      </body>
    </html>
  );
}
